workflows:
  flutter-app:
    name: Flutter App Build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PROJECT_PATH: "."
    scripts:
      - name: Install dependencies
        script: |
          cd $PROJECT_PATH
          flutter pub get
      - name: Build APK
        script: |
          cd $PROJECT_PATH
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
